apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
  labels:
    app.kubernetes.io/name: k8s-test
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 100
      template:
        metadata:
          labels:
            app.kubernetes.io/name: k8s-test
        spec:
          containers:
          - name: clearsessions
            image: docker.io/library/django_app
            imagePullPolicy: IfNotPresent
            command:
              - python
              - manage.py
              - clearsessions
            envFrom:
              - configMapRef:
                  name: django-config-map
          restartPolicy: Never