apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  labels:
    app.kubernetes.io/name: k8s-test
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 60
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-test
    spec:
      containers:
      - name: django-migrate
        image: docker.io/library/django_app
        imagePullPolicy: IfNotPresent
        command:
          - python
          - manage.py
          - migrate
        envFrom:
          - configMapRef:
              name: django-config-map
      restartPolicy: Never